version: '3'
services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_volumes
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=whatsuppd
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    command:  sh -c "yarn start:dev"
    volumes:
      - ./server/:/app
      - ./server/node_modules:/app/node_modules
    depends_on: 
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - ./web/:/app
      - ./web/node_modules:/app/node_modules