version: '3'
services:
  db:
    image: postgres:13
    container_name: whatsupp-db
    ports:
      - "5432:5432"
    volumes:
      - ./db_volumes/:/var/lib/postgresql
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=whatsuppd