version: '3'
services:
  db:
    image: postgres:10-alpine
    container_name: whatsupp-db
    ports:
      - "5432:5432"
    volumes:
      - ./db_volumes/:/var/lib/postgresql
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=whatsuppd
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: whatsupp-server
    ports:
      - "4000:4000"
    command:  sh -c "yarn && yarn start:dev"
    volumes:
      - ./server/:/app
      - ./server/node_modules:/app/node_modules
    depends_on: 
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: whatsupp-web
    command: sh -c "yarn && yarn dev"
    ports:
      - "3001:3001"
    volumes:
      - ./web/:/app
      - ./web/node_modules:/app/node_modules
    depends_on: 
      - server